name: test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.1
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run test

      - uses: codecov/codecov-action@v2
